INIT: false
mongo: true
cloud: true
db: pubmed
email: notarealemail@fake.edu
# Path you want logs printed to, eg. P:\_Projects\pyentrez\logs\pyentrez.log
output: None
retmax: 20
retmode: txt
rettype: medline
sort: relevance
verbose: 1
uri: mongodb+srv://entrez_dev:test@cluster0.tlkqq.mongodb.net/test?retryWrites=true&w=majority
host: 127.0.0.1
port: 27017
