INIT: false
mongo: true
cloud: false
db: pubmed
email: notarealemail@fake.edu
output: P:\_Projects\pyentrez\logs\pyentrez.log
retmax: 100
retmode: txt
rettype: medline
sort: relevance
verbose: 1
uri: mongodb+srv://entrez_dev:test@cluster0.tlkqq.mongodb.net/test?retryWrites=true&w=majority
host: 127.0.0.1
port: 27017
